### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by juliagorman** [talmolab/sleap-anipose#40]
I got this error when running traingulation. It did not result in a points3d.h5 file. Interestingly, this is after I updated sleap-anipose to 0.1.7, but if I log onto a computer where I am still running an older version of sleap-anipose I do not get this error and I am able to get a points3d.h5 file
![Screenshot 2023-07-30 at 5 18 48 PM](https://github.com/talmolab/sleap-anipose/assets/32439305/11c99d8e-3b62-44ba-b1bf-0280a50cf0b8)

**Comment by ericleonardis** [comment]
this was fixed by PR #47
